<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\DevStudio.Infrastructure\DevStudio.Infrastructure.csproj" />
    <ProjectReference Include="..\DevStudio.Application\DevStudio.Application.csproj" />
    <ProjectReference Include="..\DevStudio.Domain\DevStudio.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
