<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AiShop.Infrastructure\AiShop.Infrastructure.csproj" />
    <ProjectReference Include="..\AiShop.Application\AiShop.Application.csproj" />
    <ProjectReference Include="..\AiShop.Domain\AiShop.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
